name: CoWIN Checker

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  checker:
    name: 👀 Job is running
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by webhook."
